# Generated by Django 3.0.5 on 2020-04-02 15:34

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=my_app.models.course_image_path),
        ),
        migrations.AlterField(
            model_name='attachmentfiles',
            name='file',
            field=models.FileField(upload_to='attach-files-%y-%m-%d_%H:%M'),
        ),
    ]
