# Generated by Django 3.0.5 on 2020-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200402_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
