# Generated by Django 3.0.5 on 2020-04-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_course_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='alt',
            new_name='altt',
        ),
    ]
