# Generated by Django 3.0.5 on 2020-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aducation',
        ),
        migrations.AddField(
            model_name='profile',
            name='_education',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سیکل'), (2, ' دیپلم  '), (3, ' کاردانی '), (4, 'کار شناسی'), (5, 'ارشد'), (6, 'دکترا')], null=True),
        ),
    ]
